[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_solc_version = true
optimizer = true
optimizer_rounds = 200
fs_permissions = [{ access = "read", path = "./broadcast" }]


[fuzz]
runs = 10000

[invariant]
runs = 128
depth = 128
fail_on_revert = true